<?php

namespace Database\Seeders;
use App\Models\employes;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class EmployesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('employes')->insert([[
            'id' => 1,
            'nom' => "MAHAOUI",
            'prenom' => "ANNE SOPHIE",
            'mail' => "MAHAOUI@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADU",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "ADU",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>50,
        ],
        [
            'id' => 2,
            'nom' => "VANNIER",
            'prenom' => "ELODIE",
            'mail' => "VANNIER@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADU",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "ADU",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>51,
        ],
        [
            'id' => 3,
            'nom' => "LANGLAIS",
            'prenom' => "EMILIE",
            'mail' =>  "LANGLAIS@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADU",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "ADU",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>53,
        ],
        [
            'id' => 4,
            'nom' => "DEGRANGES",
            'prenom' => "BENOIT",
            'mail' => "DEGRANGES@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADU",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "ADU",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>100,
        ],
        [
            'id' => 5,
            'nom' => "GAGE",
            'prenom' => "BENOIT",
            'mail' => "GAGE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADVM",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "ADVM",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>55,
        ],
        [
            'id' => 6,
            'nom' => "PRONO",
            'prenom' => "ADELINE",
            'mail' => "PRONO@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "ADVM",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "ADVM",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>90,
        ],
        [
            'id' => 7,
            'nom' => "HARDY",
            'prenom' => "MARION",
            'mail' => "HARDY@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021090008",
        ],
        [
            'id' => 8,
            'nom' => "GERBAUT",
            'prenom' => "CLAUDINE",
            'mail' => "GERBAUT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010070",
        ],
        [
            'id' => 9,
            'nom' => "JOUBERT",
            'prenom' => "SANDRINE",
            'mail' =>  "JOUBERT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010071",
        ],
        [
            'id' => 10,
            'nom' => "JUNOT",
            'prenom' => "CORALIE",
            'mail' => "JUNOT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021060033",
        ],
        [
            'id' => 11,
            'nom' => "LOGEREAU",
            'prenom' => "PATRICIA",
            'mail' => "LOGEREAU@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010060",
        ],
        [
            'id' => 12,
            'nom' => "PESTEL",
            'prenom' => "SOPHIE",
            'mail' =>  "PESTEL@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010060",
        ],
        [
            'id' => 13,
            'nom' => "POUPARD",
            'prenom' => "ROSELINE",
            'mail' =>"POUPARD@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010062",
        ],
        [
            'id' => 14,
            'nom' => "RABAJOTIL",
            'prenom' => "STEPHANIE",
            'mail' =>"RABAJOTIL@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010063",
        ],
        [
            'id' => 15,
            'nom' => "SANSON",
            'prenom' => "ALEXANDRE",
            'mail' => "SANSON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>56,
        ],
        [
            'id' => 16,
            'nom' => "SERAMY",
            'prenom' => "EMILIE",
            'mail' =>"SERAMY@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2022050006",
        ],
        [
            'id' => 17,
            'nom' => "TARDIF",
            'prenom' => "CELINE",
            'mail' => "TARDIF@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021060034",
        ],
        [
            'id' => 18,
            'nom' => "VINCENT",
            'prenom' => "CAROLINE",
            'mail' =>"VINCENT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021060035",
        ],
        [
            'id' => 19,
            'nom' => "ZENASNI",
            'prenom' => "HOURIA",
            'mail' =>"ZENASNI@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Entraide familiale",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "Entraide familiale",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021050012",
        ],
        [
            'id' => 20,
            'nom' => "PRODHOMME",
            'prenom' => "ESTELLE",
            'mail' =>  "PRODHOMME@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Communication",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FEDERATION",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>57,
        ],
        [
            'id' => 21,
            'nom' => "CHAUVIN",
            'prenom' => "VANESSA",
            'mail' =>"CHAUVIN@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Direction",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FEDERATION",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>58,
        ],
        [
            'id' => 22,
            'nom' => "GAGLIONE",
            'prenom' => "LAURENCE",
            'mail' => "GAGLIONE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Ressources Humaines",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010014",
        ],
        [
            'id' => 23,
            'nom' => "CISSE",
            'prenom' => "ESTELLE",
            'mail' =>"CISSE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Ressources Humaines",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010045",
        ],
        [
            'id' => 24,
            'nom' => "CHATEAU ANNAUD",
            'prenom' => "EMILY",
            'mail' =>"CHATEAUANNAUD@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Ressources Humaines",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010030",
        ],
        [
            'id' => 25,
            'nom' => "GARCIN",
            'prenom' => "JOCELYNE",
            'mail' => "GARCIN@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Ressources Humaines",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010022",
        ],
        [
            'id' => 26,
            'nom' => "MELISSON",
            'prenom' => "ALINE",
            'mail' =>"MELISSON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Ressources Humaines",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010017",
        ],
        [
            'id' => 27,
            'nom' => "GAUTIER",
            'prenom' => "CATHERINE",
            'mail' => "GAUTIER@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Administratif",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010013",
        ],
        [
            'id' => 28,
            'nom' => "COLLET",
            'prenom' => "CELINE",
            'mail' => "COLLET@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' =>"Administratif",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010027",
        ],
        [
            'id' => 29,
            'nom' => "RICHARD",
            'prenom' => "NADIA",
            'mail' =>  "RICHARD@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Administratif",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010025",
        ],
        [
            'id' => 30,
            'nom' => "HYVON",
            'prenom' => "ISABELLE",
            'mail' => "HYVON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Administratif",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010016",
        ],
        [
            'id' => 31,
            'nom' => "GAUTELIER",
            'prenom' => "MARIE CHRISTINE",
            'mail' =>"GAUTELIER@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Administratif",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"HYVON",
        ],
        [
            'id' => 32,
            'nom' => "GOURMELON",
            'prenom' => "JULIE",
            'mail' =>"GOURMELON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010033",
        ],
        [
            'id' => 33,
            'nom' => "BOUTTIER",
            'prenom' => "CORINNE",
            'mail' =>  "BOUTTIER@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010015",
        ],
        [
            'id' => 34,
            'nom' => "MILLET",
            'prenom' => "BEATRICE",
            'mail' => "MILLET@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010032",
        ],
        [
            'id' => 35,
            'nom' => "DE LAFORCADE",
            'prenom' => "CAROLINE",
            'mail' => "DELAFORCADE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021100007",
        ],
        [
            'id' => 36,
            'nom' => "CHARBONNIER",
            'prenom' => "VIRGINIE",
            'mail' => "CHARBONNIER@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010023",
        ],
        [
            'id' => 37,
            'nom' => "COIFFE",
            'prenom' => "CELINE",
            'mail' => "COIFFE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Comptabilité Paie",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010046",
        ],
        [
            'id' => 38,
            'nom' => "OUDIN BOUCHEREAU",
            'prenom' => "CELINE",
            'mail' => "OUDINBOUCHEREAU@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010031",
        ],
        [
            'id' => 39,
            'nom' => "BIROUD",
            'prenom' => "COLLINE",
            'mail' => "BIROUD@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021020015",
        ],
        [
            'id' => 40,
            'nom' => "BRISBOUT",
            'prenom' => "MARION",
            'mail' => "BRISBOUT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>102,
        ],
        [
            'id' => 41,
            'nom' => "CHEVEREAU",
            'prenom' => "ROMANE",
            'mail' => "CHEVEREAU@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010044",
        ],
        [
            'id' => 42,
            'nom' => "GACHE",
            'prenom' => "AURORE",
            'mail' =>"GACHE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2022030004",
        ],
        [
            'id' => 43,
            'nom' => "LEVASSEUR",
            'prenom' => "MARION",
            'mail' =>"LEVASSEUR@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021070008",
        ],
        [
            'id' => 44,
            'nom' => "LECOURT",
            'prenom' => "STACY",
            'mail' => "LECOURT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Continuité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021090014",
        ],
        [
            'id' => 45,
            'nom' => "LEFEUVRE",
            'prenom' => "VIRGINIE",
            'mail' =>"LEFEUVRE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010029",
        ],
        [
            'id' => 46,
            'nom' => "ROPARS",
            'prenom' => "MARTINE",
            'mail' => "ROPARS@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 1,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010021",
        ],
        [
            'id' => 48,
            'nom' => "ANGOT",
            'prenom' => "MARINE",
            'mail' => "ANGOT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021090015",
        ],
        [
            'id' => 49,
            'nom' => "BARBE",
            'prenom' => "JULIE",
            'mail' => "BARBE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>'IN2021010040',
        ],[
            'id' => 50,
            'nom' => "BRUNEAU",
            'prenom' => "VALERIE",
            'mail' => "BRUNEAU@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010026",
        ],[
            'id' => 51,
            'nom' => "BUSSON",
            'prenom' => "EMELINE",
            'mail' => "BUSSON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010043",
        ],[
            'id' => 52,
            'nom' => "DAHBI",
            'prenom' => "CAROLE",
            'mail' =>"DAHBI@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010048",
        ],[
            'id' => 53,
            'nom' => "DE STEFANI",
            'prenom' => "ELISE",
            'mail' => "DESTEFAN@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010053",
        ],[
            'id' => 54,
            'nom' => "FOUCAULT",
            'prenom' => "CHLOE",
            'mail' =>  "FOUCAULT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010054",
        ],[
            'id' => 55,
            'nom' => "HOUDOUIN",
            'prenom' => "SYLVIE",
            'mail' => "HOUDOUIN@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010020",
        ],[
            'id' => 56,
            'nom' => "LAMBERT",
            'prenom' => "CATHERINE",
            'mail' => "LAMBERT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010047",
        ],[
            'id' => 57,
            'nom' => "LEBRETON",
            'prenom' => "ANAIS",
            'mail' =>"LEBRETON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010050",
        ],[
            'id' => 58,
            'nom' => "LEDON",
            'prenom' => "EMILIE",
            'mail' => "LEDON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010052",
        ],[
            'id' => 59,
            'nom' => "LESAGE",
            'prenom' => "MARIE HELENE",
            'service' => "Cadre Opérationnel Terrain",
            'mail' =>"LESAGE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010019",
        ],[
            'id' => 60,
            'nom' => "LOESEL",
            'prenom' => "MARTINE",
            'mail' => "LOESEL@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010018",
        ],[
            'id' => 61,
            'nom' => "ROBERTON",
            'prenom' => "CATHERINE",
            'mail' => "ROBERTON@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Direction Qualité Communication",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "FRASAD",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010078",
        ],[
            'id' => 62,
            'nom' => "ROBIN",
            'prenom' => "CATHERINE",
            'mail' =>"ROBIN@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOS GARDE ENFANTS",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>59,
        ],[
            'id' => 63,
            'nom' => "DESCHAMPS",
            'prenom' => "VIRGINIE",
            'mail' =>"DESCHAMPS@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021080010",
        ],[
            'id' => 64,
            'nom' => "FOULARD",
            'prenom' => "AMANDINE",
            'mail' => "FOULARD@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Qualité",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010057",
        ],[
            'id' => 65,
            'nom' => "GRIMAULT",
            'prenom' => "CECILE",
            'mail' =>"GRIMAULT@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010012",
        ],[
            'id' => 66,
            'nom' => "REGUERRE",
            'prenom' => "ARNAUD",
            'mail' =>"REGUERRE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010028",
        ],[
            'id' => 67,
            'nom' => "VALLEE",
            'prenom' => "SANDRINE",
            'mail' => "VALLEE@gmail.com",
            'tel' => NULL,
            'TypeContrat' => "CDI",
            'service' => "Cadre Opérationnel Terrain",
            'admin' => 0,
            'intitule' => NULL,
            'structure' => "SOUTIEN A DOMICILE",
            'dateEmbauche' => NULL,
            'Datefin' => NULL,
            'identifiant'=>"IN2021010008",
        ],
    ]);
    }
}
