<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([[
            'id' => 2,
            'name' => "MAHAOUI",
            'email' => "MAHAOUI@gmail.com",
            'structure' => "ADU",
            'email_verified_at' => NULL,
            'password' => '$2y$10$PRkVbnSpDGH8F7cndUuzUOJckuLceW1O67R5UwvzCVYXN98dUo1GC',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 50,
        ],[
            'id' => 3,
            'name' => "VANNIER",
            'email' => "VANNIER@gmail.com",
            'structure' => "ADU",
            'email_verified_at' => NULL,
            'password' => '$2y$10$gKPI.SBYSFeMLMl/9wh.NerIjOKNZZWhRMBx9irYjqYuHsn9Ij3fa',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 51,
        ],[
            'id' => 4,
            'name' => "LANGLAIS",
            'email' => "LANGLAIS@gmail.com",
            'structure' => "ADU",
            'email_verified_at' => NULL,
            'password' => '$2y$10$LNa7NranNLhn9KoDp3Rt/uFSsx49jHmaf4pb7jH5yxjy3YiyCax9u',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 53,
        ],[
            'id' => 6,
            'name' => "GAGE",
            'email' => "GAGE@gmail.com",
            'structure' => "ADVM",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 1,
            'identifiant' => 55,
        ],[
            'id' => 7,
            'name' => "PRONO",
            'email' => "PRONO@gmail.com",
            'structure' => "ADVM",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 90,
        ],[
            'id' => 8,
            'name' => "HARDY",
            'email' => "HARDY@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 1,
            'identifiant' => 'IN2021090008',
        ],[
            'id' => 9,
            'name' => "GERBAUT",
            'email' => "GERBAUT@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010070',
        ],[
            'id' => 10,
            'name' => "JOUBERT",
            'email' => "JOUBERT@gmail.com",
            'structure' => "",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010071',
        ],[
            'id' => 11,
            'name' => "JUNOT",
            'email' => "JUNOT@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021060033',
        ],[
            'id' => 12,
            'name' => "LOGEREAU",
            'email' => "LOGEREAU@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010060',
        ],[
            'id' => 13,
            'name' => "PESTEL",
            'email' => "PESTEL@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010060',
        ],[
            'id' => 14,
            'name' => "POUPARD",
            'email' => "POUPARD@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010062',
        ],[
            'id' => 15,
            'name' => "RABAJOTIL",
            'email' => "RABAJOTIL@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010063',
        ],[
            'id' => 16,
            'name' => "SANSON",
            'email' => "SANSON@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 56,
        ],[
            'id' => 17,
            'name' => "SERAMY",
            'email' => "SERAMY@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2022050006',
        ],[
            'id' => 18,
            'name' => "TARDIF",
            'email' => "TARDIF@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021060034',
        ],[
            'id' => 19,
            'name' => "VINCENT",
            'email' => "VINCENT@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021060035',
        ],[
            'id' => 20,
            'name' => "ZENASNI",
            'email' => "ZENASNI@gmail.com",
            'structure' => "Entraide familiale",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021050012',
        ],[
            'id' => 21,
            'name' => "PRODHOMME",
            'email' => "PRODHOMME@gmail.com",
            'structure' => "COMMUNICATION",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 57,
        ],[
            'id' => 22,
            'name' => "CHAUVIN",
            'email' => "CHAUVIN@gmail.com",
            'structure' => "FEDERATION",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 1,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 58,
        ],[
            'id' => 23,
            'name' => "ANGOT",
            'email' => "ANGOT@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021090015',
        ],[
            'id' => 24,
            'name' => "GAGLIONE",
            'email' => "GAGLIONE@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010014',
        ],[
            'id' => 25,
            'name' => "CISSE",
            'email' => "CISSE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010045',
        ],[
            'id' => 26,
            'name' => "CHATEAU ANNAUD",
            'email' => "CHATEAUANNAUD@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010030',
        ],[
            'id' => 27,
            'name' => "GARCIN",
            'email' => "GARCIN@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010022',
        ],[
            'id' => 28,
            'name' => "MELISSON",
            'email' => "MELISSON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010017',
        ],[
            'id' => 29,
            'name' => "GAUTIER",
            'email' => "GAUTIER@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010013',
        ],[
            'id' => 30,
            'name' => "COLLET",
            'email' => "COLLET@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010027',
        ],[
            'id' => 31,
            'name' => "RICHARD",
            'email' => "RICHARD@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010025',
        ],[
            'id' => 32,
            'name' => "HYVON",
            'email' => "HYVON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010016',
        ],[
            'id' => 33,
            'name' => "GAUTELIER",
            'email' => "GAUTELIER@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'HYVON',
        ],[
            'id' => 34,
            'name' => "GOURMELON",
            'email' => "GOURMELON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010033',
        ],[
            'id' => 35,
            'name' => "BOUTTIER",
            'email' => "BOUTTIER@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010015',
        ],[
            'id' => 36,
            'name' => "MILLET",
            'email' => "MILLET@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010032',
        ],[
            'id' => 37,
            'name' => "DE LAFORCADE",
            'email' => "DELAFORCADE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021100007',
        ],[
            'id' => 38,
            'name' => "CHARBONNIER",
            'email' => "CHARBONNIER@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010023',
        ],[
            'id' => 39,
            'name' => "COIFFE",
            'email' => "COIFFE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010046',
        ],[
            'id' => 40,
            'name' => "OUDIN BOUCHEREAU",
            'email' => "OUDINBOUCHEREAU@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010031',
        ],[
            'id' => 41,
            'name' => "BIROUD",
            'email' => "BIROUD@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021020015',
        ],[
            'id' => 42,
            'name' => "CHEVEREAU",
            'email' => "CHEVEREAU@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010044',
        ],[
            'id' => 43,
            'name' => "GACHE",
            'email' => "GACHE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2022030004',
        ],[
            'id' => 44,
            'name' => "LEVASSEUR",
            'email' => "LEVASSEUR@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021070008',
        ],[
            'id' => 45,
            'name' => "HERTAUX",
            'email' => "HERTAUX@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2022050005',
        ],[
            'id' => 46,
            'name' => "LECOURT",
            'email' => "LECOURT@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021090014',
        ],[
            'id' => 47,
            'name' => "LEFEUVRE",
            'email' => "LEFEUVRE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010029',
        ],[
            'id' => 48,
            'name' => "ROPARS",
            'email' => "ROPARS@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010021',
        ],[
            'id' => 49,
            'name' => "BARBE",
            'email' => "BARBE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010040',
        ],[
            'id' => 50,
            'name' => "BRUNEAU",
            'email' => "BRUNEAU@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010026',
        ],[
            'id' => 51,
            'name' => "BUSSON",
            'email' => "BUSSON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010043',
        ],[
            'id' => 52,
            'name' => "DAHBI",
            'email' => "DAHBI@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010048',
        ],[
            'id' => 53,
            'name' => "DE STEFANI",
            'email' => "DESTEFAN@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010053',
        ],[
            'id' => 54,
            'name' => "FOUCAULT",
            'email' => "FOUCAULT@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010054',
        ],[
            'id' => 55,
            'name' => "HOUDOUIN",
            'email' => "HOUDOUIN@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010020',
        ],[
            'id' => 56,
            'name' => "LAMBERT",
            'email' => "LAMBERT@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' =>'IN2021010047',
        ],[
            'id' => 57,
            'name' => "LEBRETON",
            'email' => "LEBRETON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010050',
        ],[
            'id' => 58,
            'name' => "LEDON",
            'email' => "LEDON@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010052',
        ],[
            'id' => 59,
            'name' => "LESAGE",
            'email' => "LESAGE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010019',
        ],[
            'id' => 60,
            'name' => "LOESEL",
            'email' => "LOESEL@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010018',
        ],[
            'id' => 61,
            'name' => "ROBERTON",
            'email' => "ROBERTON@gmail.com",
            'structure' => "FRASAD",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 1,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010078',
        ],[
            'id' => 62,
            'name' => "ROBIN",
            'email' => "ROBIN@gmail.com",
            'structure' => "SOS GARDE ENFANTS",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 59,
        ],[
            'id' => 63,
            'name' => "DESCHAMPS",
            'email' => "DESCHAMPS@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021080010',
        ],[
            'id' => 64,
            'name' => "FOULARD",
            'email' => "FOULARD@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010057',
        ],[
            'id' => 65,
            'name' => "GRIMAULT",
            'email' => "GRIMAULT@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010012',
        ],[
            'id' => 66,
            'name' => "REGUERRE",
            'email' => "REGUERRE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => 'IN2021010028',
        ],[
            'id' => 67,
            'name' => "VALLEE",
            'email' => "VALLEE@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => "IN2021010008",
        ],
        [
            'id' => 68,
            'name' => "DEGRANGES",
            'email' => "DEGRANGES@gmail.com",
            'structure' => "ADU",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => "100",
        ],
        [
            'id' => 69,
            'name' => "BRISBOUT",
            'email' => "BRISBOUT@gmail.com",
            'structure' => "SOUTIEN A DOMICILE",
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7iMritVZGtm7zB7u2hlpOwTuFbfLHFM.Q8RBv87xMTpG.xY1YTaq',
            'remember_token' => NULL,
            'direction' => 0,
            'created_at' => "2022-06-18 05:19:36",
            'updated_at' => "2022-06-18 05:19:36",
            'admin' => 0,
            'identifiant' => "102",
        ],
        
    ]);
    }
}
